"""Create applications table

Revision ID: 001
Revises: None
Create Date: 2025-01-01 00:00:00.000000

MySQL-compatible: UUIDs stored as CHAR(36), generated by MySQL UUID() function.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "applications",
        # UUIDs stored as CHAR(36) in MySQL; Python generates them via uuid.uuid4()
        sa.Column(
            "app_id",
            sa.String(36),
            primary_key=True,
            server_default=sa.text("(UUID())"),
        ),
        sa.Column(
            "pixel_id",
            sa.String(36),
            unique=True,
            nullable=False,
            server_default=sa.text("(UUID())"),
        ),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("company_name", sa.String(150), nullable=True),
        sa.Column("job_title", sa.String(150), nullable=True),
        sa.Column("persona_used", sa.String(20), nullable=True),
        sa.Column("hr_email", sa.String(255), nullable=True),
        sa.Column(
            "status",
            sa.String(20),
            nullable=False,
            server_default="applied",
        ),
        sa.Column("source_type", sa.String(10), nullable=True),
        sa.Column("source_url", sa.Text, nullable=True),
        sa.Column("pdf_path", sa.Text, nullable=True),
        sa.Column("jd_text", sa.Text, nullable=True),
        sa.Column(
            "tailoring_skipped",
            sa.Boolean,
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column("email_subject", sa.Text, nullable=True),
        sa.Column("email_body", sa.Text, nullable=True),
        sa.Column("initial_ats_score", sa.Integer, nullable=True),
        sa.Column("final_ats_score", sa.Integer, nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
            onupdate=sa.func.now(),
        ),
        mysql_engine="InnoDB",
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
    )

    op.create_index("idx_applications_status", "applications", ["status"])
    op.create_index("idx_applications_pixel_id", "applications", ["pixel_id"])
    op.create_index("idx_applications_timestamp", "applications", ["timestamp"])


def downgrade() -> None:
    op.drop_index("idx_applications_timestamp", table_name="applications")
    op.drop_index("idx_applications_pixel_id", table_name="applications")
    op.drop_index("idx_applications_status", table_name="applications")
    op.drop_table("applications")
